/**
 * Editor E2E — Phase 3, Task 11.
 *
 * Strategy
 * --------
 * We have FOUR scenarios; only the first runs without external state:
 *
 *   1. Unauth redirect           — works in CI with zero setup.
 *   2. Editor renders + preview  — needs signed-in session.
 *   3. Draft restore on reload   — needs signed-in session + a working
 *                                  `/write` page (which itself needs a
 *                                  Supabase admin client to look up the
 *                                  username).
 *   4. Image upload              — needs signed-in session + a real
 *                                  Supabase Storage bucket.
 *
 * Auth bypass (choice (b) in the task brief): we picked the env-var-plus-
 * header shim because the Phase 1 NextAuth setup uses the DB session
 * strategy (Supabase adapter) — a pure cookie injection would still need a
 * real session row, so it doesn't get us anywhere on CI. The shim lives
 * in `lib/auth.ts::getSession` and only activates when:
 *
 *     NODE_ENV !== 'production'
 *  && process.env.E2E_TEST_AUTH_USER_ID is set
 *  && the request header `x-e2e-auth: 1` is present
 *
 * Test 1 omits the header so it still observes a null session and gets
 * redirected. Tests 2–4 send the header via `page.setExtraHTTPHeaders`
 * (browser) or `extraHTTPHeaders` on `page.request` (REST).
 *
 * Supabase dependency
 * -------------------
 * `/write` calls `createAdminSupabaseClient()` to look up the author's
 * username. When `SUPABASE_SERVICE_ROLE_KEY` is missing in the test env,
 * that call throws and the page 500s. We therefore SKIP tests 2–4 when
 * the key isn't present. Test 1 short-circuits via `redirect()` before
 * the Supabase call, so it runs everywhere.
 *
 * The image upload (test 4) is doubly DB-dependent (Storage). Same skip.
 *
 * Files / fixtures
 * ----------------
 * The PNG used by test 4 is generated by sharp in `test.beforeAll` and
 * written to the OS temp dir, so we don't check a binary into git.
 */
import { test, expect, type Page } from '@playwright/test'
import sharp from 'sharp'

const HEADER_E2E_AUTH = { 'x-e2e-auth': '1' }

const SUPABASE_AVAILABLE = !!process.env.SUPABASE_SERVICE_ROLE_KEY
const SKIP_REASON =
  'requires a real Supabase instance (set SUPABASE_SERVICE_ROLE_KEY to run)'

/**
 * Convenience: make `page` send the E2E shim header on every request.
 * Equivalent to adding `headers: HEADER_E2E_AUTH` to every fetch the
 * browser performs.
 */
async function signIn(page: Page): Promise<void> {
  await page.setExtraHTTPHeaders(HEADER_E2E_AUTH)
}

test.describe('Editor — /write', () => {
  // -------------------------------------------------------------------------
  // 1. Unauth redirect
  // -------------------------------------------------------------------------
  test('redirects unauthenticated visitors to /auth/signin?callbackUrl=/write', async ({
    page,
  }) => {
    const response = await page.goto('/write')
    // After redirect, the response we observe is the signin page.
    expect(response?.status()).toBe(200)
    // `redirect()` from next/navigation emits the literal path (not URL-
    // encoded) in the query string. Accept either form to stay robust to
    // a future Next behaviour flip.
    const finalUrl = page.url()
    expect(finalUrl).toContain('/auth/signin')
    expect(finalUrl).toMatch(/callbackUrl=(%2F|\/)write/)
  })

  // -------------------------------------------------------------------------
  // 2. Editor renders for a signed-in user; preview updates on input.
  // -------------------------------------------------------------------------
  test('signed-in user sees editor + preview that reflects body markdown', async ({
    page,
  }) => {
    test.skip(!SUPABASE_AVAILABLE, SKIP_REASON)

    await signIn(page)
    const response = await page.goto('/write')
    expect(response?.status()).toBe(200)

    // Editor shell rendered (slug preview is a stable anchor — it's the
    // only fixed-position read-only element on the page).
    await expect(page.getByTestId('slug-preview')).toBeVisible()

    // Click into the CodeMirror editor and type a heading.
    const editor = page.getByTestId('codemirror-editor').locator('.cm-content')
    await editor.click()
    await editor.fill('# Hello, e2e world')

    // The preview pane is rendered on a debounced server compile. Wait
    // for the heading to materialise in it. We don't rely on a testid on
    // the rendered DOM because next-mdx-remote leaves it bare — but the
    // <h1> text is unique to the post body.
    await expect(
      page.getByRole('heading', { name: 'Hello, e2e world', level: 1 }),
    ).toBeVisible({ timeout: 10_000 })
  })

  // -------------------------------------------------------------------------
  // 3. Draft restore on reload.
  // -------------------------------------------------------------------------
  test('typing then reloading prompts a draft-restore modal', async ({ page }) => {
    test.skip(!SUPABASE_AVAILABLE, SKIP_REASON)

    await signIn(page)
    await page.goto('/write')

    const editor = page.getByTestId('codemirror-editor').locator('.cm-content')
    await editor.click()
    await editor.fill('# Persisted draft\n\nbody text here')

    // The auto-save debounce is 300ms in tests (see playwright.config.ts
    // env block). Wait for the "draft saved" status to confirm the write
    // landed in localStorage.
    await expect(page.getByTestId('draft-status')).toContainText(/draft saved/i, {
      timeout: 5_000,
    })

    // Reload and expect the restore modal.
    await page.reload()

    const dialog = page.getByRole('dialog', { name: /restore your last draft/i })
    await expect(dialog).toBeVisible({ timeout: 5_000 })

    await dialog.getByRole('button', { name: /^restore$/i }).click()

    // After clicking Restore, the dialog is gone and the editor body has
    // our text again. CodeMirror renders content inside .cm-content as
    // multiple span nodes — assert on the visible text instead.
    await expect(dialog).toBeHidden()
    await expect(
      page.getByTestId('codemirror-editor').locator('.cm-content'),
    ).toContainText('Persisted draft')
  })

  // -------------------------------------------------------------------------
  // 4. /api/uploads returns a valid URL for a small PNG.
  // -------------------------------------------------------------------------
  test('POST /api/uploads accepts a valid PNG and returns a URL', async ({
    request,
  }) => {
    test.skip(!SUPABASE_AVAILABLE, SKIP_REASON)

    // Generate a 10x10 RGBA PNG on the fly so we don't commit a binary
    // fixture. sharp writes a valid PNG that passes the route's
    // magic-byte sniff + dimension cap.
    const pngBuf = await sharp({
      create: {
        width: 10,
        height: 10,
        channels: 4,
        background: { r: 255, g: 0, b: 0, alpha: 1 },
      },
    })
      .png()
      .toBuffer()

    const res = await request.post('/api/uploads?bucket=post-images', {
      headers: HEADER_E2E_AUTH,
      multipart: {
        file: {
          name: 'sample.png',
          mimeType: 'image/png',
          buffer: pngBuf,
        },
      },
    })

    expect(res.status()).toBe(200)
    const body = (await res.json()) as { url?: string }
    expect(typeof body.url).toBe('string')
    expect(body.url).toMatch(/^https?:\/\//)
  })
})
